# Generated by Django 4.2.3 on 2023-08-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_product_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cropping',
        ),
    ]
