# Generated by Django 4.2.3 on 2023-08-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_remove_product_cropping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.variation')),
            ],
        ),
    ]
