# Generated by Django 4.2.3 on 2023-08-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
