# Generated by Django 4.2.3 on 2023-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rprice',
            field=models.IntegerField(null=True),
        ),
    ]
