# Generated by Django 4.2.3 on 2023-08-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_product_rprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discount_percentage',
            new_name='discount',
        ),
    ]
