# Generated by Django 4.2.3 on 2023-08-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_rename_discount_offer_discount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discount_percentage',
            new_name='discount',
        ),
    ]
