# Generated by Django 4.2.3 on 2023-08-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='referral_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
