# Generated by Django 4.2.3 on 2023-08-26 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_wallet_updated_at_alter_wallet_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='referral_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
