# Generated by Django 4.2.3 on 2023-09-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_coupon_redeemed_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_id',
            field=models.CharField(default='', max_length=8),
        ),
    ]
