# Generated by Django 4.2.3 on 2023-09-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userprofile_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_id',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
