# Generated by Django 4.2.3 on 2023-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userprofile_referral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
