# Generated by Django 4.2.3 on 2023-09-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_payment_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
